#!/usr/bin/env bash
# Mostly stolen from http://raspberrypi.stackexchange.com/a/43336/39077

# test comment
# hope bash doesn't freak out!

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INSTALL_DIR="${DIR}/.."
HOME_DIR="${INSTALL_DIR}/.."

set -e

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

info 'Moving any left-over test images bask into ${INSTALL_DIR}/static/raspi-imported-photos'
info "so git doesn't freak out."
mv "${INSTALL_DIR}"/test-* "${INSTALL_DIR}/static/raspi-imported-photos" || true

info 'Disabling DPMS (Energy Star) features'
xset -dpms

info 'Disabling screensaver'
xset s off

info 'Stopping video device from blanking'
xset s noblank

info 'Updating & rebuilding code'
cd "${INSTALL_DIR}"
sleep 30 # Give Pi time to connect to network
git pull origin master
npm prune
npm install
npm run build

info "Temporarily moving test images out of ${INSTALL_DIR}/static/raspi-imported-photos"
mv "${INSTALL_DIR}/static/raspi-imported-photos"/test-* "${INSTALL_DIR}"

info "rsync-ing images from /media/usb0 to ${INSTALL_DIR}/static/raspi-imported-photos"
rsync -vhr --delete \
  --exclude='*/' \
  --exclude='test-*' \
  --exclude='README.md' \
  --include='*.jpg' \
  --include='*.jpeg' \
  --include='*.JPG' \
  --include='*.JPEG' \
  --include='*.png' \
  --include='*.gif' \
  '/media/usb0/' "${INSTALL_DIR}/static/raspi-imported-photos/"

info 'Starting server in background'
npm run start:production > "$INSTALL_DIR/server.log" 2>&1 &

info 'Giving server time to start up...'
sleep 60

# Start browser
$DIR/startup-subscript &
startup_subscript_PID=$!

info 'Giving browser time to startup & fullscreening'
xte 'sleep 60' 'key F11' > "${INSTALL_DIR}/xte.log" 2>&1

# Wait for startup-subscript to finish before exiting
FAIL=0

wait $startup_subscript_PID || let 'FAIL+=1'

if [ "$FAIL" == "0" ]; then
  success 'Chromium closed with no errors!'
  user 'Press any key to continue...'
  read -n1 -r key
  exit 0
else
  fail 'Chromium closed with errors! Check the logs!'
  user 'Press any key to continue...'
  read -n1 -r key
  exit 1
fi
