#!/usr/bin/env bash
# Mostly stolen from http://raspberrypi.stackexchange.com/a/43336/39077
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INSTALL_DIR="${DIR}/.."
HOME_DIR="${INSTALL_DIR}/.."

set -e

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
}

info 'Disabling DPMS (Energy Star) features'
xset -dpms

info 'Disabling screensaver'
xset s off

info 'Stopping video device from blanking'
xset s noblank

info 'Updating & rebuilding code'
cd "${INSTALL_DIR}"
sleep 30 # Give Pi time to connect to network
git pull origin master
npm prune
npm install
npm run build

info "Temporarily moving test images out of ${INSTALL_DIR}/static/raspi-imported-photos"
mv "${INSTALL_DIR}/static/raspi-imported-photos"/test-* "${INSTALL_DIR}"

info "rsync-ing images from /media/usb0 to ${INSTALL_DIR}/static/raspi-imported-photos"
rsync -vhr --delete "/media/usb0"/*.jpg "${INSTALL_DIR}/static/raspi-imported-photos" || true
rsync -vhr --delete "/media/usb0"/*.jpeg "${INSTALL_DIR}/static/raspi-imported-photos" || true
rsync -vhr --delete "/media/usb0"/*.JPG "${INSTALL_DIR}/static/raspi-imported-photos" || true
rsync -vhr --delete "/media/usb0"/*.JPEG "${INSTALL_DIR}/static/raspi-imported-photos" || true
rsync -vhr --delete "/media/usb0"/*.png "${INSTALL_DIR}/static/raspi-imported-photos" || true
rsync -vhr --delete "/media/usb0"/*.gif "${INSTALL_DIR}/static/raspi-imported-photos" || true

info 'Starting server in background'
npm run start:production > "$INSTALL_DIR/server.log" 2>&1 &

info 'Giving server time to start up...'
sleep 60

# Start browser
$DIR/startup-subscript &

info 'Giving browser time to startup & fullscreening, refreshing'
xte 'sleep 30' 'key F11' 'sleep 5' 'key F5'

exit 0
