#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INSTALL_DIR="${DIR}/.."
HOME_DIR="${INSTALL_DIR}/.."

set -e

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

info 'Starting epiphany in koisk mode'
epiphany-browser http://localhost:3000 > $INSTALL_DIR/epiphany.log

info 'Restoring test images (to avoid git merge commits ;-) )'
mv "${INSTALL_DIR}"/test-* "${INSTALL_DIR}/static/raspi-imported-photos"
